[workers]
worker1 ansible_host=ec2-54-163-37-104.compute-1.amazonaws.com
worker2 ansible_host=ec2-54-221-7-96.compute-1.amazonaws.com


[master]
master1 ansible_host=ec2-52-54-160-85.compute-1.amazonaws.com


[all:vars]
ansible_ssh_user=ubuntu
ansible_ssh_private_key_file=./aws-ec2.pem
